
const main=document.querySelector('.article');
const toast=document.getElementById('toast');
let toastTimer;
function notify(t){toast.textContent=t;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2200);}
document.querySelectorAll('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const el=document.getElementById(btn.dataset.code);const text=el.querySelector('code').textContent;let copied=false;try{await navigator.clipboard.writeText(text);copied=true;}catch(e){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();try{copied=document.execCommand('copy');}catch(e){}t.remove();}if(copied){btn.textContent='Скопировано';setTimeout(()=>btn.textContent='Копировать',1600);notify('Текст примера скопирован');}else{const r=document.createRange();r.selectNodeContents(el);const s=window.getSelection();s.removeAllRanges();s.addRange(r);notify('Пример выделен — нажмите Ctrl+C / Cmd+C');}}));
const input=document.getElementById('search');let found=[],current=-1,timer;
function clearMarks(){main.querySelectorAll('mark').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));main.normalize();found=[];current=-1;}
function highlight(){clearMarks();const q=input.value.trim().toLowerCase();if(q.length<2){document.getElementById('count').textContent='';return;}const w=document.createTreeWalker(main,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode()){const n=w.currentNode;if(n.parentElement.closest('button,script,style'))continue;if(n.nodeValue.toLowerCase().includes(q))nodes.push(n);}for(const n of nodes){const v=n.nodeValue,low=v.toLowerCase();let pos=0,idx=low.indexOf(q);const f=document.createDocumentFragment();while(idx!==-1){f.append(document.createTextNode(v.slice(pos,idx)));const m=document.createElement('mark');m.textContent=v.slice(idx,idx+q.length);f.append(m);pos=idx+q.length;idx=low.indexOf(q,pos);}f.append(document.createTextNode(v.slice(pos)));n.replaceWith(f);}found=[...main.querySelectorAll('mark')];document.getElementById('count').textContent=found.length?'0 / '+found.length:'0';}
function moveMatch(delta=1){if(!found.length)return;if(current>=0)found[current].classList.remove('current');current=(current+delta+found.length)%found.length;found[current].classList.add('current');found[current].scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('count').textContent=(current+1)+' / '+found.length;}
input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(highlight,180);});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(timer);if(!found.length)highlight();moveMatch(e.shiftKey?-1:1);}if(e.key==='Escape'){input.value='';clearMarks();document.getElementById('count').textContent='';input.blur();}});document.getElementById('next').addEventListener('click',()=>moveMatch(1));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus();input.select();}});
document.getElementById('menu').addEventListener('click',()=>document.querySelector('aside').classList.toggle('open'));document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{if(window.innerWidth<801)document.querySelector('aside').classList.remove('open');}));
document.addEventListener('click',e=>{if(window.innerWidth<801&&!e.target.closest('aside')&&!e.target.closest('#menu'))document.querySelector('aside').classList.remove('open');});
const headings=[...main.querySelectorAll('h3')];function progress(){const available=document.documentElement.scrollHeight-window.innerHeight;const frac=available?Math.min(1,window.scrollY/available):0;const offset=window.innerWidth<801?0:(window.innerWidth<=1100?230:278);document.querySelector('.progress').style.width=((window.innerWidth-offset)*frac)+'px';let selected;for(const h of headings){if(h.getBoundingClientRect().top<150)selected=h;}document.querySelectorAll('.nav-section').forEach(a=>a.classList.toggle('active',!!selected&&a.getAttribute('href')==='#'+selected.id));}window.addEventListener('scroll',progress,{passive:true});window.addEventListener('resize',progress);progress();
